### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hbaniecki** [DominikRafacz/deepdep#6]
### Goals
- [x] package popularity
- [x] package versions
- [x] Shiny app to explore packages
- [x] ship to CRAN
- [ ] namespace/environment dependencies

### Enchancements
- [x] rebuild site (vignettes)
- [x] ~add several color palettes~ nicer palette
- [ ] add popularity (downloads) as plot mapping (size?) 
- [x] add dependency version to the plot
- [x] add downloads plot
- [x] change deps_types to dep_type/dependency_type /+s?
- [x] better quality Description in DESCRIPTION
- [ ] ~finish cheatsheet~
- [x] add package version and date to the plot
- [ ] ~add making parallel queries to CRAN (if possible)~
- [ ] add possibility of replacing node points/labels with logos; central only, labelled only or all
